### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by nejatian** [in28minutes/SpringBootForBeginners#1]
hi, I'm new to spring boot and I am trying to use @jointable annotation in my project. but I have a serious problem. can you please help me solve this problem?
[https://stackoverflow.com/q/61070135/9276162](url)
thank you for your further response.

**Comment by AbhishekAnand24** [comment]
When I am clicking on the Stackoverflow URL mentioned by you, Url is redirecting me to Github page not stackoverflow page.

Request you to please update it.

**Comment by nejatian** [comment]
thank you for your respond, I have solved my problem.
